### ISSUE TITLE
fireworks example in tests causes freeze after pressing escape

### ISSUE THREAD

**Issue by ukscone** [breakintoprogram/agon-bbc-basic#22]
if I 
*CD /TESTS
LOAD "FIREWORKS.BAS"
RUN

and press escape it stops but doesn't return to the BASIC prompt it just freezes, pressing warmboot keysequence doesn't do anything and to get back to a usable Agon I have to press the reset button

**Comment by leventp** [comment]
Pressing escape works for me (BASIC 1.04 and VDP and MOS 1.03)

**Comment by breakintoprogram** [comment]
Going to mark this as 'Won't Do' as I cannot replicate this on MOS 1.03. Please note that it does set most of the palette to black, so you may have to switch to a different mode to reset the palette, say MODE 2.
