### ISSUE TITLE
Logical Screen Coordinates are off in Mode 1 and Mode 2

### ISSUE THREAD

**Issue by leventp** [breakintoprogram/agon-bbc-basic#28]
Logical screen coordinates look fine in MODE 0 but slightly off in MODE 1 and 2.  Tested using the code:
10 CLS
20 MOVE 0,0
30 DRAW 1279, 1023

**Comment by breakintoprogram** [comment]
It only seems to be out by a fraction. Going to close this issue as 'Won't Do' as it is an unavoidable artefact of using screen resolutions that are not evenly dividable by 1280 and 1024.
