### ISSUE TITLE
CLS does not clear sprites. It would be nice if it incorporated the command VDU 23,27,7,0, so even the sprites would be cleared.

### ISSUE THREAD

**Issue by TheByteAttic** [breakintoprogram/agon-bbc-basic#3]

**Comment by breakintoprogram** [comment]
### Proposed Fix
Leave CLS as it is for the moment, there may be a use case for clearing the screen but not the sprites. Modify the function set_mode to reset the sprites on mode change.

**Comment by breakintoprogram** [comment]
Implemented in modules

- 1.01 VDP

**Comment by breakintoprogram** [comment]
Modified in VDP 1.03 to also clear the sprites after CLS.
