### ISSUE TITLE
Cannot concatenate command after FX

### ISSUE THREAD

**Issue by astralaster** [breakintoprogram/agon-bbc-basic#45]
The following code should print "TEST", but does not:

*FX 19 : PRINT "TEST"

But this does print "TEST1" and "TEST2" as expected:

PRINT "TEST1" : PRINT "TEST2"

So it looks like it is not possible to concatenate anything after a *FX command?

**Comment by breakintoprogram** [comment]
Yes, this is by design; the same behaviour as on the BBC Model B.
