### ISSUE TITLE
Mode Command not validating input

### ISSUE THREAD

**Issue by MackW** [breakintoprogram/agon-bbc-basic#51]
Tested on a BBC (haven't tested on Z80 BBC Basic though)
the command
MODE 0' 
changes mode and then throws a "Syntax Error"
on a BBC it throws the error without doing anything.
It looks like the basic is not validating the parameter correctly.

**Comment by breakintoprogram** [comment]
Just tested it on my Tatung Einstein and can confirm that this is correct behaviour for BBC BASIC for Z80. It would also be a bit of a pig to correct it.
