### ISSUE TITLE
Consider Displaying BBC BASIC (Agon) Version info on startup

### ISSUE THREAD

**Issue by oldpatientsea** [breakintoprogram/agon-bbc-basic#54]
![BASICVERSION](https://github.com/breakintoprogram/agon-bbc-basic/assets/129397698/62c5617a-f267-48d0-99c8-7616acfbf53b)

BASIC currently shows the version number for the BBC BASIC (Z80) code on which it has been based rather than the BBC BASIC (Agon) version number which is more important for determining if a user has the correct version of BASIC for their firmware.

If it showed both version numbers on startup, this might help speed up the process of finding answers when new users post problems on github, facebook, discord, etc

**Comment by ZbigniewB** [comment]
They are actually version (3.00) and **release** (1.05) numbers.

**Comment by envenomator** [comment]
I've seen too many people run into problems, thinking they were on the latest release of bbcbasic for the Agon, while actually they were running an older one. It would really help users to display something like
'BBC Basic (Z80) Version 3.00, Agon release 1.0x' at each startup
