### ISSUE TITLE
Consider Changing Version Numbers to Be Consistent with VDP and MOS

### ISSUE THREAD

**Issue by oldpatientsea** [breakintoprogram/agon-bbc-basic#55]
At present, new users are expected to know that MOS/VDP 1.03 go with BBC BASIC (Agon) 1.04.

It would be simpler if MOS, VDP and BASIC shared identical major and minor version numbers where they are compatible, with new, upgraded compatible versions of BBC BASIC taking a patch release number, eg BBC BASIC (Agon) 1.04.02. 

That way users would know that major and minor numbers need to be identical for a three components of the Quark firmware.

**Comment by breakintoprogram** [comment]
I'm going to close this after some consideration as 'Won't Do', as the projects are likely to be released over time with different cadences, but will make sure that there is a compatibility chart up in the documentation so that folks know what versions they need.
