### ISSUE TITLE
Implement the SYS keyword/command

### ISSUE THREAD

**Issue by stevesims** [breakintoprogram/agon-bbc-basic#58]
It would be useful to have a SYS command to allow easier access to the underlying MOS function calls.

Acorn added the SYS command to BBC BASIC V, and Richard Russell has included SYS in his more recent BBC BASIC interpreters.

Without the implementation of a SYS command accessing MOS functions is restrictively hard as it requires custom z80 assembler code to be written.  This puts it out of reach for all but the most experienced developers.

**Comment by breakintoprogram** [comment]
Hi, great ideas, but no plans on expanding this Z80 version much beyond stock BASIC IV.
