### ISSUE TITLE
Add more modern BBC BASIC features

### ISSUE THREAD

**Issue by stevesims** [breakintoprogram/agon-bbc-basic#59]
The z80 version of BBC BASIC dates back a long way and whilst it is broadly equivalent and compatible with BBC BASIC version 4 it is missing out on quite a few keywords and features that Acorn added to BASIC V and are present in other newer versions of BASIC produced by Richard Russell.

We should consider improving the BASIC interpreter to include some of these newer features.

Examples of a few features I've missed so far has been bit-shifting operators `>>` and `<<`, support for specifying the filename on the first line of a program, multi-line `IF` statements, `CASE` statements and `WHILE` loops.  As I'd already noted in #58  including a `SYS` call would be very useful.

One other thing that would be really good to support is the ability to load in libraries with the `INSTALL` statement.  This would be very useful for sharing code and would for instance make using [the agon512k library](https://github.com/TurboVega/agon512k) much simpler.

**Comment by breakintoprogram** [comment]
Hi, great ideas, but no plans on expanding this Z80 version much beyond stock BASIC IV.
