### ISSUE TITLE
Bad Program reported for plain text .BAS files

### ISSUE THREAD

**Issue by stevesims** [breakintoprogram/agon-bbc-basic#60]
I ran into an issue where attempting to load a plain text .BAS resulted in me seeing a `Bad program` error.

On investigation I found this was caused by the file having LF character line endings.  Changing the file to use CRLF fixed the issue.

As many modern computers and editors now default to using LF only for line endings BASIC should really support that.

**Comment by breakintoprogram** [comment]
Fixed - now handles files with CR/LF, LF/CR and with no trailing line at end.

**Comment by breakintoprogram** [comment]
Also rolled into agon-bbc-basic-adl.
