### ISSUE TITLE
*LOAD crash

### ISSUE THREAD

**Issue by DjPoke** [breakintoprogram/agon-bbc-basic#63]
Hi,
I can't get this command to work.
I've made an assembler program with ADL=0 and ORG=&F700, use HIMEM at &F6FF, and try to *LOAD, but without success.

```
*LOAD myfile.bin F700
*LOAD myfile.bin &F700
*LOAD "myfile.bin" F700
```
Theese lines fake to load, but do nothing, crash, or send an error message.
Is there a syntax I should know ?

**Comment by DjPoke** [comment]
I also tried this, but I get garbages on the screen :
`OSCLI("LOAD routines.bin &F700")`

**Comment by DjPoke** [comment]
... or may be it loads only assembler programs saved with *SAVE ?

**Comment by lennart-benschop** [comment]
As a start you need to specify the full 24-bit address on LOAD, like
*LOAD myfile.bin &4F700

**Comment by DjPoke** [comment]
Thank you
